[package]
name = "trustify-module-storage"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
trustify-common = { workspace = true }

anyhow = { workspace = true }
async-compression = { workspace = true, features = ["tokio", "zstd"] }
bytes = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
http = "0.2"                    # workspace version conflicts with rust-s3 0.35
log = { workspace = true }
rust-s3 = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["full"] }
tracing = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
test-log = { workspace = true, features = ["log", "trace"] }
test-context = { workspace = true }
