[package]
name = "trustify-module-storage"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
trustify-common = { workspace = true }

anyhow = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
rust-s3 = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["full"] }

[dev-dependencies]
serde_json = { workspace = true }
sha2 = { workspace = true }
test-log = { workspace = true, features = ["log", "trace"] }
test-context = { workspace = true }
