[package]
name = "trustify-module-ui"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
actix-web = { workspace = true }
actix-web-static-files = { workspace = true }
anyhow = { workspace = true }
trustify-ui = { workspace = true }
utoipa = { workspace = true }
