pub mod http;

use actix_cors::Cors;
use actix_web::{
    App, Error,
    body::MessageBody,
    dev::{ServiceFactory, ServiceRequest, ServiceResponse},
    http::header,
    middleware::{Compress, DefaultHeaders, Logger},
    web,
};
use actix_web_extras::middleware::Condition;
use actix_web_httpauth::{extractors::bearer::BearerAuth, middleware::HttpAuthentication};
use futures::{FutureExt, future::LocalBoxFuture};
use opentelemetry_instrumentation_actix_web::{RequestMetrics, RequestTracing};
use std::sync::Arc;
use trustify_auth::{
    authenticator::{Authenticator, actix::openid_validator},
    authorizer::Authorizer,
};
use trustify_common::middleware::StdMiddleware;

#[derive(Default)]
pub struct AppOptions {
    pub cors: Option<Cors>,
    pub authenticator: Option<Arc<Authenticator>>,
    pub authorizer: Authorizer,
    pub logger: Option<Logger>,
    pub tracing_logger: Option<RequestTracing>,
    pub metrics: Option<RequestMetrics>,
    pub security_headers: Option<SecurityHeaders>,
}

/// Defense-in-depth HTTP response headers applied to every response.
///
/// `Content-Security-Policy` and `Strict-Transport-Security` are configurable
/// because their correct values are deployment-specific (e.g. CSP `connect-src`
/// must include the OIDC issuer for the UI's auth flow). An empty string omits
/// that individual header.
#[derive(Clone, Debug)]
pub struct SecurityHeaders {
    pub content_security_policy: String,
    pub strict_transport_security: String,
}

impl SecurityHeaders {
    /// Build the actix `DefaultHeaders` middleware for this configuration.
    ///
    /// `DefaultHeaders` only sets a header when a handler has not already set
    /// it, so per-route overrides remain possible.
    fn into_middleware(self) -> DefaultHeaders {
        let mut headers = DefaultHeaders::new()
            .add((header::X_CONTENT_TYPE_OPTIONS, "nosniff"))
            .add((header::X_FRAME_OPTIONS, "DENY"))
            .add((header::REFERRER_POLICY, "strict-origin-when-cross-origin"));
        if !self.content_security_policy.is_empty() {
            headers = headers.add((
                header::CONTENT_SECURITY_POLICY,
                self.content_security_policy,
            ));
        }
        if !self.strict_transport_security.is_empty() {
            headers = headers.add((
                header::STRICT_TRANSPORT_SECURITY,
                self.strict_transport_security,
            ));
        }
        headers
    }
}

/// create a new authenticator
#[allow(clippy::type_complexity)]
pub fn new_auth(
    auth: Option<Arc<Authenticator>>,
) -> Condition<
    HttpAuthentication<
        BearerAuth,
        impl Fn(
            ServiceRequest,
            BearerAuth,
        ) -> LocalBoxFuture<'static, Result<ServiceRequest, (Error, ServiceRequest)>>,
    >,
> {
    Condition::from_option(auth.map(move |authenticator| {
        HttpAuthentication::bearer(move |req, auth| {
            let authenticator = authenticator.clone();
            Box::pin(async move { openid_validator(req, auth, authenticator).await }).boxed_local()
        })
    }))
}

/// Build a new HTTP app in a consistent way.
///
/// Adding middleware to an HTTP app is tricky, as it requires to think about the order of adding.
/// This function should capture all the logic requires to properly set up a common application,
/// allowing some choices in the process.
pub fn new_app(
    options: AppOptions,
) -> App<
    impl ServiceFactory<
        ServiceRequest,
        Config = (),
        Response = ServiceResponse<impl MessageBody>,
        Error = Error,
        InitError = (),
    >,
> {
    // The order of execution is last added becomes first to be executed. So if you read the
    // following lines, read them from end to start! Middleware for services will be executed after
    // the middleware here.
    App::new()
        // Reject mutating requests when in read-only mode (runs last, after auth)
        .std_middleware()
        // Handle authentication, might fail and return early
        .wrap(new_auth(options.authenticator))
        // Handle authorization
        .app_data(web::Data::new(options.authorizer))
        // Handle CORS requests, this might finish early and not pass requests to the next entry
        .wrap(Condition::from_option(options.cors))
        // Next, record metrics for the request (should never fail)
        .wrap(Condition::from_option(options.metrics))
        // Compress everything
        .wrap(Compress::default())
        // First log the request, so that we know what happens (can't fail)
        .wrap(Condition::from_option(options.logger))
        // Enable tracing logger if configured
        .wrap(Condition::from_option(options.tracing_logger))
        // Set security response headers on every response (outermost, so it
        // also covers error responses generated by inner middleware)
        .wrap(Condition::from_option(
            options
                .security_headers
                .map(SecurityHeaders::into_middleware),
        ))
}

#[cfg(test)]
mod test {
    use super::*;
    use actix_web::{HttpResponse, test, web};

    #[actix_web::test]
    async fn security_headers_applied_to_responses() {
        let app = test::init_service(
            new_app(AppOptions {
                security_headers: Some(SecurityHeaders {
                    content_security_policy: "frame-ancestors 'none'".to_string(),
                    strict_transport_security: "max-age=31536000; includeSubDomains".to_string(),
                }),
                ..Default::default()
            })
            .route("/", web::get().to(|| async { HttpResponse::Ok().finish() })),
        )
        .await;

        let resp = test::call_service(&app, test::TestRequest::get().uri("/").to_request()).await;
        let headers = resp.headers();

        assert_eq!(headers.get("x-content-type-options").unwrap(), "nosniff");
        assert_eq!(headers.get("x-frame-options").unwrap(), "DENY");
        assert_eq!(
            headers.get("referrer-policy").unwrap(),
            "strict-origin-when-cross-origin"
        );
        assert_eq!(
            headers.get("content-security-policy").unwrap(),
            "frame-ancestors 'none'"
        );
        assert_eq!(
            headers.get("strict-transport-security").unwrap(),
            "max-age=31536000; includeSubDomains"
        );
    }

    #[actix_web::test]
    async fn empty_csp_and_hsts_are_omitted() {
        let app = test::init_service(
            new_app(AppOptions {
                security_headers: Some(SecurityHeaders {
                    content_security_policy: String::new(),
                    strict_transport_security: String::new(),
                }),
                ..Default::default()
            })
            .route("/", web::get().to(|| async { HttpResponse::Ok().finish() })),
        )
        .await;

        let resp = test::call_service(&app, test::TestRequest::get().uri("/").to_request()).await;
        let headers = resp.headers();

        assert!(headers.get("content-security-policy").is_none());
        assert!(headers.get("strict-transport-security").is_none());
        // Static headers are still present.
        assert_eq!(headers.get("x-frame-options").unwrap(), "DENY");
    }

    #[actix_web::test]
    async fn no_security_headers_when_disabled() {
        let app = test::init_service(
            new_app(AppOptions {
                security_headers: None,
                ..Default::default()
            })
            .route("/", web::get().to(|| async { HttpResponse::Ok().finish() })),
        )
        .await;

        let resp = test::call_service(&app, test::TestRequest::get().uri("/").to_request()).await;
        assert!(resp.headers().get("x-frame-options").is_none());
    }
}
