apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: tests
spec:
  description: >-
    Sample description
  params:
  - name: SNAPSHOT
    type: string
  results:
  - name: TEST_OUTPUT
    description: Test output
  steps:
  - name: basic-test
    image: quay.io/redhat-user-workloads/trusted-content-tenant/rhtpa/rhtpa:latest
    env:
      - name: SNAPSHOT
        value: $(params.SNAPSHOT)
    script: |
      ./test.sh
