apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: tests
spec:
  params:
    - name: SNAPSHOT
      type: string
  tasks:
    - name: test
      params:
        - name: SNAPSHOT
          value: "$(params.SNAPSHOT)"
      taskSpec:
        params:
          - name: SNAPSHOT
            type: string
        steps:
          - name: test-output
            image: docker.io/bitnami/kubectl:latest
            env:
              - name: SNAPSHOT
                value: "$(params.SNAPSHOT)"
              - name: NAMESPACE
                value: "$(context.pipelineRun.namespace)"
            script: |
              #!/usr/bin/bash
              set -euxo pipefail

              IMAGE=$(echo "$SNAPSHOT" | jq -r '.components[0].containerImage')
              echo "Extracted image: $IMAGE"
              kubectl create job test-hello -n $NAMESPACE --image=$IMAGE
              kubectl wait --for=condition=complete job/test-hello --timeout=120s
              LOGS=$(kubectl logs -l job-name=test-hello -n $NAMESPACE)
              # kubectl delete job --ignore-not-found test-hello -n $NAMESPACE
              echo $LOGS
