apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: tests
  namespace: trusted-content-tenant
spec:
  params:
    - name: SNAPSHOT
      type: string
  tasks:
    - name: test
      params:
        - name: SNAPSHOT
          value: "$(params.SNAPSHOT)"
      taskSpec:
        params:
          - name: SNAPSHOT
            type: string
        steps:
          - image: quay.io/redhat-appstudio/konflux-test:latest
            env:
              - name: SNAPSHOT
                value: $(params.SNAPSHOT)
            script: |
              echo -e "${SNAPSHOT}"

