[package]
name = "trustify-module-ingestor"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
trustify-common = { workspace = true }
trustify-cvss = { workspace = true }
trustify-entity = { workspace = true }
trustify-module-storage = { workspace = true }
trustify-module-analysis = { workspace = true }

actix-web = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
cpe = { workspace = true }
csaf = { workspace = true }
cve = { workspace = true }
cyclonedx-bom = { workspace = true }
hex = { workspace = true }
humantime = { workspace = true }
jsn = { workspace = true }
lenient_semver = { workspace = true }
log = { workspace = true }
osv = { workspace = true, features = ["schema"] }
packageurl = { workspace = true }
parking_lot = { workspace = true }
quick-xml = { workspace = true }
roxmltree = { workspace = true }
sbom-walker = { workspace = true }
sea-orm = { workspace = true }
sea-query = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yml = { workspace = true }
spdx = { workspace = true }
spdx-expression = { workspace = true }
spdx-rs = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["serde-well-known"] }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true, features = ["v7"] }
zip = { workspace = true }

[dev-dependencies]
trustify-auth = { workspace = true }
trustify-test-context = { workspace = true }

actix-http = { workspace = true }
rand = { workspace = true }
rstest = { workspace = true }
serde_yml = { workspace = true }
test-context = { workspace = true }
test-log = { workspace = true, features = ["log", "trace"] }
zip = { workspace = true }
