name: ci

on:
  push:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo rm -Rf ${JAVA_HOME_8_X64}
          sudo rm -Rf ${JAVA_HOME_11_X64}
          sudo rm -Rf ${JAVA_HOME_17_X64}
          sudo rm -Rf ${RUBY_PATH}
          df -h

      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Format
        run: cargo fmt --check
      - name: Check
        run: cargo check
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings -D clippy::unwrap_used -D clippy::expect_used
      - name: Test
        run: cargo test -- --nocapture
        env:
          RUST_LOG: warn,sqlx=error,sea_orm=error
      - name: Export and Validate Generated Openapi Spec
        run: |
          cargo xtask openapi
          if ! git diff --quiet; then
              echo "::error::Uncommitted changes (run 'cargo xtask openapi' after making api changes)"
              exit 1
          fi
      - name: Ensure schemas are up-to-date
        run: |
          cargo xtask generate-schemas
          if ! git diff --quiet; then
              echo "::error::Uncommitted changes (run 'cargo xtask generate-schemas' after making changes to the models)"
              exit 1
          fi
