name: sync-upstream

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: tgymnich/fork-sync@v2.0.10
      with:
        base: main
        head: main 
        token: ${{ secrets.GITHUB_TOKEN }}
        merge_method: rebase
